### ISSUE TITLE
rename_existing field in cfgs causing "Existing command not found"

### ISSUE THREAD

**Issue by Poofjunior** [TypQxQ/KTC#32]
On Klipper v0.12.0-290, M104.cfg and M09.cfg throw errors on the `rename_existing` field.
![image](https://github.com/user-attachments/assets/206ad234-effb-413d-8291-6397f4a325ba)

However, removing the `rename_existing` field removes the error.

Did something happen to `M104.1` and `M109.1` commands in later releases?
Is the `M104` command expecting `M104.1` to be called in the macro?

This is on a fresh install of Klipper and KTC.

**Comment by TypQxQ** [comment]
Hi! This is the first time I encounter this.
Have you defined an extruder? Maybe klipper only loads M104 when an extruder is configured.
Otherwise I can't see why it wouldn't find M104 command.

**Comment by Poofjunior** [comment]
Oof--yup--that looks like it! I was building from a bare config without any extruders defined yet.
Thanks for the hand--and for putting this project together!
