### ISSUE TITLE
Update KTC_TOOL_SET_STATE to KTC_SET_STATE in error messages and example configs

### ISSUE THREAD

**Issue by ngolshan** [TypQxQ/KTC#34]
Accidentally used an old syntax `KTC_TOOL_SET_STATE` based on the complete example config. Got an error that this command is unknown, because it's been updated to `KTC_SET_STATE`. 

The main documentation is up to date, but the internal error message still suggests the old syntax. 

![image](https://github.com/user-attachments/assets/49e2d482-ab8b-420f-80d0-0bd178278a7d)

**Comment by ngolshan** [comment]
After updating to the new `KTC_SET_STATE` syntax, my error is resolved.

**Comment by TypQxQ** [comment]
Fixed in latest update.
