### ISSUE TITLE
KTC_TOOL_OFFSET_SAVE appears to set the last used XYZ parameters even when none are provided. 

### ISSUE THREAD

**Issue by ngolshan** [TypQxQ/KTC#36]
`KTC_TOOL_OFFSET_SAVE` is giving me somewhat unexpected behavior

Before using the command to set an offset, `KTC_TOOL_OFFSET_SAVE T=0` effectively "reads" the currently stored offsets for T0. 

Running `KTC_TOOL_OFFSET_SAVE T=0 X=-0.438000 Y=-32.505000 Z=3.18225` sets offsets as expected. 

Then, running `KTC_TOOL_OFFSET_SAVE T=1' immediately afterwards sets **T1** to the XYZ offsets just used above, even though none were included with the command.

The expected behavior from my interpretation of the documentation would be to read the current offsets without setting anything. I would not expect any existing offsets to change from running the command without explicitly providing an X/Y/Z parameter to the command. 

<img width="637" alt="image" src="https://github.com/user-attachments/assets/fa56cae0-9c68-4812-9b57-4b7915bb2e01">

**Comment by TypQxQ** [comment]
Hi!

I couldn't reproduce this but made a debuging version of ktc.py that should help us track the problem. Please swap your ktc.py with this, restart Klipper and try again. Post the results from ktc.log.
https://github.com/TypQxQ/KTC/blob/KTC_TOOL_OFFSET_SAVE-debug/extensions/ktc.py

Here is my output:
```
06:30:12 - DEBUG: Tool 0 offset before: [-0.438, -32.505, 3.18225]
06:30:12 - DEBUG: Offset before: [-0.438, -32.505, 3.18225]
06:30:12 - DEBUG: Setting X to 0.0
06:30:12 - DEBUG: Setting Y to 0.0
06:30:12 - DEBUG: Setting Z to 0.0
06:30:12 - DEBUG: Offset after: [0.0, 0.0, 0.0]
06:30:12 - DEBUG: Tool 0 offset after: [0.0, 0.0, 0.0]
06:30:12 Tool 0 offset set to: [0.0, 0.0, 0.0]
06:30:17 - DEBUG: Tool 1 offset before: [-1.438, -1.505, 1.18225]
06:30:17 - DEBUG: Offset before: [-1.438, -1.505, 1.18225]
06:30:17 - DEBUG: Setting X to 0.0
06:30:17 - DEBUG: Setting Y to 0.0
06:30:17 - DEBUG: Setting Z to 0.0
06:30:17 - DEBUG: Offset after: [0.0, 0.0, 0.0]
06:30:17 - DEBUG: Tool 1 offset after: [0.0, 0.0, 0.0]
06:30:17 Tool 1 offset set to: [0.0, 0.0, 0.0]
06:30:31 - DEBUG: Tool 0 offset before: [0.0, 0.0, 0.0]
06:30:31 - DEBUG: Offset before: [0.0, 0.0, 0.0]
06:30:31 - DEBUG: Offset after: [0.0, 0.0, 0.0]
06:30:31 - DEBUG: Tool 0 offset after: [0.0, 0.0, 0.0]
06:30:31 Tool 0 offset set to: [0.0, 0.0, 0.0]
06:30:32 - DEBUG: Tool 1 offset before: [0.0, 0.0, 0.0]
06:30:32 - DEBUG: Offset before: [0.0, 0.0, 0.0]
06:30:32 - DEBUG: Offset after: [0.0, 0.0, 0.0]
06:30:32 - DEBUG: Tool 1 offset after: [0.0, 0.0, 0.0]
06:30:32 Tool 1 offset set to: [0.0, 0.0, 0.0]
06:31:07 - DEBUG: Tool 1 offset before: [0.0, 0.0, 0.0]
06:31:07 - DEBUG: Offset before: [0.0, 0.0, 0.0]
06:31:07 - DEBUG: Setting X to 0.1
06:31:07 - DEBUG: Setting Y to 0.1
06:31:07 - DEBUG: Setting Z to 0.1
06:31:07 - DEBUG: Offset after: [0.1, 0.1, 0.1]
06:31:07 - DEBUG: Tool 1 offset after: [0.1, 0.1, 0.1]
06:31:07 Tool 1 offset set to: [0.1, 0.1, 0.1]
06:31:13 - DEBUG: Tool 0 offset before: [0.0, 0.0, 0.0]
06:31:13 - DEBUG: Offset before: [0.0, 0.0, 0.0]
06:31:13 - DEBUG: Offset after: [0.0, 0.0, 0.0]
06:31:13 - DEBUG: Tool 0 offset after: [0.0, 0.0, 0.0]
06:31:13 Tool 0 offset set to: [0.0, 0.0, 0.0]

```

Regards,
Andrei

**Comment by ngolshan** [comment]
Sorry for the delay! Finally got around to testing this. Now I can't reproduce the problem either! 

With this debug version of KTC.py, here are my results. They're correct and the commands are working as I would expect. I'm going to switch back to the original ktc.py next and post the results of the same console sequence.

**Console Input**
`09:11:31 PM
RESTART
09:11:31 PM
Klipper state: Disconnect
09:11:39 PM
 Toolchanger Jubilee disengaged
09:11:39 PM
 Toolchanger Jubilee initialized unlocked, without tool
09:13:58 PM
KTC_TOOL_OFFSET_SAVE
09:13:58 PM
No tool specified and no active tool
09:14:06 PM
KTC_TOOL_OFFSET_SAVE T=0
09:14:06 PM
Tool 0 offset set to: [-0.335, -32.374, 3.18225]
09:14:20 PM
KTC_TOOL_OFFSET_SAVE T=1
09:14:21 PM
Tool 1 offset set to: [-0.339, -32.885, 3.261625]
09:15:10 PM
KTC_TOOL_OFFSET_SAVE T=0 X=0.1 Y=0.2 Z=0.3
09:15:10 PM
Tool 0 offset set to: [0.1, 0.2, 0.3]
09:15:26 PM
KTC_TOOL_OFFSET_SAVE T=1
09:15:26 PM
Tool 1 offset set to: [-0.339, -32.885, 3.261625]
09:15:57 PM
KTC_TOOL_OFFSET_SAVE T=1 X=0.4 Y=0.5 Z=0.6
09:15:57 PM
Tool 1 offset set to: [0.4, 0.5, 0.6]
09:16:07 PM
KTC_TOOL_OFFSET_SAVE T=0
09:16:07 PM
Tool 0 offset set to: [0.1, 0.2, 0.3]`

**Logfile Output**
`09:30:08 KTC Log Ready
09:30:08 - - TRACE: Initalizing ktc_toolchanger Jubilee.
09:30:10 - - TRACE: ktc_toolchanger.engage(): Setting state to READY.
09:30:10 - - TRACE: ktc.active_tool set to: tool_none
09:32:33 - DEBUG: Tool 0 offset before: [-0.335, -32.374, 3.18225]
09:32:33 - DEBUG: Offset before: [-0.335, -32.374, 3.18225]
09:32:33 - DEBUG: Offset after: [-0.335, -32.374, 3.18225]
09:32:33 - DEBUG: Tool 0 offset after: [-0.335, -32.374, 3.18225]
09:32:33 Tool 0 offset set to: [-0.335, -32.374, 3.18225]
09:32:51 - DEBUG: Tool 1 offset before: [-0.339, -32.885, 3.261625]
09:32:51 - DEBUG: Offset before: [-0.339, -32.885, 3.261625]
09:32:51 - DEBUG: Offset after: [-0.339, -32.885, 3.261625]
09:32:51 - DEBUG: Tool 1 offset after: [-0.339, -32.885, 3.261625]
09:32:51 Tool 1 offset set to: [-0.339, -32.885, 3.261625]
09:33:02 - DEBUG: Tool 0 offset before: [-0.335, -32.374, 3.18225]
09:33:02 - DEBUG: Offset before: [-0.335, -32.374, 3.18225]
09:33:02 - DEBUG: Setting X to 0.1
09:33:02 - DEBUG: Setting Y to 0.2
09:33:02 - DEBUG: Setting Z to 0.3
09:33:02 - DEBUG: Offset after: [0.1, 0.2, 0.3]
09:33:02 - DEBUG: Tool 0 offset after: [0.1, 0.2, 0.3]
09:33:02 Tool 0 offset set to: [0.1, 0.2, 0.3]
09:33:08 - DEBUG: Tool 1 offset before: [-0.339, -32.885, 3.261625]
09:33:08 - DEBUG: Offset before: [-0.339, -32.885, 3.261625]
09:33:08 - DEBUG: Offset after: [-0.339, -32.885, 3.261625]
09:33:08 - DEBUG: Tool 1 offset after: [-0.339, -32.885, 3.261625]
09:33:08 Tool 1 offset set to: [-0.339, -32.885, 3.261625]
09:33:33 - DEBUG: Tool 1 offset before: [-0.339, -32.885, 3.261625]
09:33:33 - DEBUG: Offset before: [-0.339, -32.885, 3.261625]
09:33:33 - DEBUG: Setting X to 0.4
09:33:33 - DEBUG: Setting Y to 0.5
09:33:33 - DEBUG: Setting Z to 0.6
09:33:33 - DEBUG: Offset after: [0.4, 0.5, 0.6]
09:33:33 - DEBUG: Tool 1 offset after: [0.4, 0.5, 0.6]
09:33:33 Tool 1 offset set to: [0.4, 0.5, 0.6]
09:33:48 - DEBUG: Tool 0 offset before: [0.1, 0.2, 0.3]
09:33:48 - DEBUG: Offset before: [0.1, 0.2, 0.3]
09:33:48 - DEBUG: Offset after: [0.1, 0.2, 0.3]
09:33:48 - DEBUG: Tool 0 offset after: [0.1, 0.2, 0.3]
09:33:48 Tool 0 offset set to: [0.1, 0.2, 0.3]`

**Comment by ngolshan** [comment]
and with the original `ktc.py` in place, i'm no longer getting the behavior I was before - which is great, but also frustrating, because I can't explain my initial results!

Thanks for your debugging effort. Sorry I also could not reproduce the issue. Feel free to close this one. 

**Console Input/Output with original `ktc.py`**
```
09:41:48 PM
 Toolchanger Jubilee disengaged
09:41:48 PM
 Toolchanger Jubilee initialized unlocked, without tool
09:42:51 PM
KTC_TOOL_OFFSET_SAVE T=0 X=-0.335 Y=-32.374 Z=3.18225
09:42:51 PM
Tool 0 offset set to: [-0.335, -32.374, 3.18225]
09:42:59 PM
KTC_TOOL_OFFSET_SAVE T=1 X=-0.339 Y=-32.885 Z=3.261625
09:42:59 PM
Tool 1 offset set to: [-0.339, -32.885, 3.261625]
09:43:14 PM
KTC_TOOL_OFFSET_SAVE T=0
09:43:14 PM
Tool 0 offset set to: [-0.335, -32.374, 3.18225]
09:43:37 PM
KTC_TOOL_OFFSET_SAVE T=1
09:43:37 PM
Tool 1 offset set to: [-0.339, -32.885, 3.261625]
09:44:03 PM
KTC_TOOL_OFFSET_SAVE T=0 X=0.1 Y=0.2 Z=0.3
09:44:03 PM
Tool 0 offset set to: [0.1, 0.2, 0.3]
09:44:10 PM
KTC_TOOL_OFFSET_SAVE T=1
09:44:10 PM
Tool 1 offset set to: [-0.339, -32.885, 3.261625]
09:44:22 PM
KTC_TOOL_OFFSET_SAVE T=1 X=0.4 Y=0.5 Z=0.6
09:44:22 PM
Tool 1 offset set to: [0.4, 0.5, 0.6]
09:44:26 PM
KTC_TOOL_OFFSET_SAVE T=0
09:44:27 PM
Tool 0 offset set to: [0.1, 0.2, 0.3]
```
