### ISSUE TITLE
Unhandled exception during run

### ISSUE THREAD

**Issue by woe616** [TypQxQ/KTC#40]
I've been getting a NoneType error on printer reboot for the past few days. This only occurs if I do a firmware start or otherwise reboot klipper but restarting the host pi and the printer starts and operates fine until I restart the firmware again.

I'm no python expert so I'm not able to figure this out myself.

Log shows this:

  File "/home/user/klipper/klippy/extras/ktc_tool.py", line 353, in get_status
    "offset": [self.offset[i] + self._ktc.global_offset[i] for i in range(3)],
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/klipper/klippy/extras/ktc_tool.py", line 353, in <listcomp>
    "offset": [self.offset[i] + self._ktc.global_offset[i] for i in range(3)],
               ~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
Transition to shutdown state: Unhandled exception during run


Full log attached. 

[klippy.log](https://github.com/user-attachments/files/17867795/klippy.log)

**Comment by woe616** [comment]
Managed to resolve this by using mainsailos instead. Previously was using fluidd installed with kiauh but using the exact same config. Not sure why it works now but I'm happy enough using this. 

Thanks

**Comment by TypQxQ** [comment]
That is fantastic news. I did try it using Fluid with KIAUH last year so I don’t know either. 
Happy for you!

**Comment by anttix** [comment]
The issue is still present with klipper v0.13.0-373-g6465921a, fluidd v1.34.4 and fluidd-config v1.2.1-0-g807175d7 running on debian Trixie based bare-bones distro.

It looks like there is a race condition between KTC initializing its tools objects and Moonraker / Fluidd querying the status of all printer objects. Simplest workaround is to apply this patch

```
diff --git a/extensions/ktc_tool.py b/extensions/ktc_tool.py
index edcffbd..b58a23d 100644
--- a/extensions/ktc_tool.py
+++ b/extensions/ktc_tool.py
@@ -344,6 +344,9 @@ class KtcTool(KtcBaseToolClass, KtcConstantsClass):
                         ex.active_to_standby_delay)

     def get_status(self, eventtime=None):  # pylint: disable=unused-argument
+        if not self._ktc:
+            return { }
+
         status = {
             "name": self.name,
             "number": self.number,
```

@TypQxQ  can you help to reopen this bug as I don't have permissions to do so. Thank you!
